# Generated by Django 6.0.6 on 2026-07-17 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMemo',
            fields=[
                ('id', models.BigAutoField(db_column='id_memorando', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='codigo', editable=False, help_text='Código gerado pelo sistema. Exemplo: MRO00001-01.', max_length=30, null=True, unique=True, verbose_name='Código')),
                ('revision', models.PositiveSmallIntegerField(db_column='revisao', default=1, verbose_name='Revisão')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], db_column='status', default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('work_source', models.CharField(choices=[('ACCESS', 'Access'), ('HUB', 'Daruix Hub')], db_column='origem_obra', default='ACCESS', max_length=20, verbose_name='Origem da obra')),
                ('legacy_work_id', models.IntegerField(blank=True, db_column='obra_origem_id', null=True, verbose_name='ID da obra no legado')),
                ('legacy_proposal_id', models.IntegerField(blank=True, db_column='proposta_origem_id', null=True, verbose_name='ID da proposta no legado')),
                ('cost_center', models.CharField(blank=True, db_column='centro_custo', default='', max_length=50, verbose_name='Centro de custo')),
                ('work_name', models.CharField(blank=True, db_column='nome_obra', default='', max_length=180, verbose_name='Nome da obra')),
                ('client_name', models.CharField(blank=True, db_column='nome_cliente', default='', max_length=255, verbose_name='Cliente')),
                ('client_document', models.CharField(blank=True, db_column='documento_cliente', default='', max_length=50, verbose_name='Documento do cliente')),
                ('shipping_date', models.DateField(blank=True, db_column='data_remessa', null=True, verbose_name='Data da remessa')),
                ('subject', models.CharField(blank=True, db_column='assunto', default='', max_length=255, verbose_name='Assunto')),
                ('attention_to', models.CharField(blank=True, db_column='aos_cuidados_de', default='', max_length=180, verbose_name='Aos cuidados de')),
                ('notes', models.TextField(blank=True, db_column='observacoes', default='', verbose_name='Observações')),
                ('sent_at', models.DateTimeField(blank=True, db_column='enviado_em', null=True, verbose_name='Enviado em')),
                ('cancelled_at', models.DateTimeField(blank=True, db_column='cancelado_em', null=True, verbose_name='Cancelado em')),
                ('cancellation_reason', models.TextField(blank=True, db_column='motivo_cancelamento', default='', verbose_name='Motivo do cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('cancelled_by', models.ForeignKey(blank=True, db_column='cancelado_por_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_shipment_memos', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('created_by', models.ForeignKey(db_column='criado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_shipment_memos', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('revised_from', models.ForeignKey(blank=True, db_column='revisado_de_id', help_text='Memorando anterior que originou esta revisão. Fica vazio na primeira versão.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_revisions', to='memorando_remessas.shipmentmemo', verbose_name='Revisado a partir de')),
                ('sent_by', models.ForeignKey(blank=True, db_column='enviado_por_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_shipment_memos', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('updated_by', models.ForeignKey(db_column='atualizado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='updated_shipment_memos', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Memorando de remessa',
                'verbose_name_plural': 'Memorandos de remessa',
                'db_table': 'memorandos_remessa',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='memo_status_created_idx'), models.Index(fields=['legacy_work_id'], name='memo_legacy_work_idx'), models.Index(fields=['cost_center'], name='memo_cost_center_idx'), models.Index(fields=['shipping_date'], name='memo_shipping_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='memo_revision_gte_1')],
            },
        ),
    ]
