# Generated by Django 6.0.6 on 2026-07-17 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorando_remessas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMemoResponsible',
            fields=[
                ('id', models.BigAutoField(db_column='id_memorando_responsavel', primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(db_column='responsavel_principal', default=False, verbose_name='Responsável principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Adicionado em')),
                ('added_by', models.ForeignKey(db_column='adicionado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='added_shipment_memo_responsibles', to=settings.AUTH_USER_MODEL, verbose_name='Adicionado por')),
                ('shipment_memo', models.ForeignKey(db_column='id_memorando', on_delete=django.db.models.deletion.CASCADE, related_name='responsible_links', to='memorando_remessas.shipmentmemo', verbose_name='Memorando')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='responsible_shipment_memos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Responsável pelo memorando',
                'verbose_name_plural': 'Responsáveis pelos memorandos',
                'db_table': 'memorando_remessa_responsaveis',
                'ordering': ['-is_primary', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('shipment_memo', 'user'), name='uq_memorando_responsavel_usuario'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('shipment_memo',), name='uq_memorando_responsavel_principal')],
            },
        ),
    ]
