# Generated by Django 6.0.6 on 2026-07-17 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorando_remessas', '0002_shipmentmemoresponsible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMemoOption',
            fields=[
                ('id', models.BigAutoField(db_column='id_memorando_opcao', primary_key=True, serialize=False)),
                ('option_type', models.CharField(choices=[('ESPECIE', 'Espécie'), ('FINALIDADE', 'Finalidade'), ('SOLICITACAO', 'Solicitação')], db_column='tipo_opcao', max_length=20, verbose_name='Tipo')),
                ('code', models.SlugField(db_column='codigo', help_text='Identificador estável usado pela API. Exemplo: carta, documento, aprovacao.', max_length=80, verbose_name='Código')),
                ('name', models.CharField(db_column='nome', max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, db_column='descricao', default='', verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(db_column='ordem', default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(db_column='ativo', default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Opção de memorando',
                'verbose_name_plural': 'Opções de memorando',
                'db_table': 'memorando_remessa_opcoes',
                'ordering': ['option_type', 'order', 'name'],
                'indexes': [models.Index(fields=['option_type', 'is_active', 'order'], name='memo_opcao_tipo_ativo_idx')],
                'constraints': [models.UniqueConstraint(fields=('option_type', 'code'), name='uq_memorando_opcao_tipo_codigo')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentMemoOptionSelection',
            fields=[
                ('id', models.BigAutoField(db_column='id_memorando_opcao_selecionada', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Selecionado em')),
                ('option', models.ForeignKey(db_column='id_opcao', on_delete=django.db.models.deletion.PROTECT, related_name='memo_selections', to='memorando_remessas.shipmentmemooption', verbose_name='Opção')),
                ('selected_by', models.ForeignKey(db_column='selecionado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='selected_shipment_memo_options', to=settings.AUTH_USER_MODEL, verbose_name='Selecionado por')),
                ('shipment_memo', models.ForeignKey(db_column='id_memorando', on_delete=django.db.models.deletion.CASCADE, related_name='option_selections', to='memorando_remessas.shipmentmemo', verbose_name='Memorando')),
            ],
            options={
                'verbose_name': 'Opção selecionada do memorando',
                'verbose_name_plural': 'Opções selecionadas dos memorandos',
                'db_table': 'memorando_remessa_opcoes_selecionadas',
                'ordering': ['option__option_type', 'option__order', 'option__name'],
            },
        ),
        migrations.AddField(
            model_name='shipmentmemo',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='shipment_memos', through='memorando_remessas.ShipmentMemoOptionSelection', to='memorando_remessas.shipmentmemooption', verbose_name='Opções selecionadas'),
        ),
        migrations.AddIndex(
            model_name='shipmentmemooptionselection',
            index=models.Index(fields=['shipment_memo'], name='memo_opcao_selec_mem_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentmemooptionselection',
            index=models.Index(fields=['option'], name='memo_opcao_selec_opc_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentmemooptionselection',
            constraint=models.UniqueConstraint(fields=('shipment_memo', 'option'), name='uq_memorando_opcao_selecionada'),
        ),
    ]
