# Generated by Django 6.0.6 on 2026-07-17 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorando_remessas', '0003_shipmentmemooption_shipmentmemooptionselection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMemoSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_column='chave', default='shipment_memo', max_length=50, unique=True, verbose_name='Chave')),
                ('current_value', models.PositiveBigIntegerField(db_column='valor_atual', default=0, verbose_name='Valor atual')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Sequência de memorando',
                'verbose_name_plural': 'Sequências de memorando',
                'db_table': 'memorando_remessa_sequencias',
            },
        ),
        migrations.AddField(
            model_name='shipmentmemo',
            name='sequence_number',
            field=models.PositiveBigIntegerField(blank=True, db_column='numero_sequencial', editable=False, null=True, verbose_name='Número sequencial'),
        ),
        migrations.AddConstraint(
            model_name='shipmentmemo',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence_number__isnull', False)), fields=('sequence_number', 'revision'), name='uq_memo_sequencia_revisao'),
        ),
    ]
