# Generated by Django 6.0.6 on 2026-07-17 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorando_remessas', '0004_shipmentmemosequence_shipmentmemo_sequence_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMemoHistory',
            fields=[
                ('id', models.BigAutoField(db_column='id_memorando_historico', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CRIADO', 'Criado'), ('ALTERADO', 'Alterado'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado'), ('REVISAO_CRIADA', 'Revisão criada'), ('ARQUIVO_ADICIONADO', 'Arquivo adicionado'), ('ARQUIVO_REMOVIDO', 'Arquivo removido')], db_column='acao', max_length=30, verbose_name='Ação')),
                ('description', models.TextField(blank=True, db_column='descricao', default='', verbose_name='Descrição')),
                ('before_data', models.JSONField(blank=True, db_column='dados_anteriores', default=dict, verbose_name='Dados anteriores')),
                ('after_data', models.JSONField(blank=True, db_column='dados_posteriores', default=dict, verbose_name='Dados posteriores')),
                ('metadata', models.JSONField(blank=True, db_column='metadados', default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('actor', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='shipment_memo_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('shipment_memo', models.ForeignKey(db_column='id_memorando', on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='memorando_remessas.shipmentmemo', verbose_name='Memorando')),
            ],
            options={
                'verbose_name': 'Histórico do memorando',
                'verbose_name_plural': 'Históricos dos memorandos',
                'db_table': 'memorando_remessa_historicos',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['shipment_memo', '-created_at'], name='memo_hist_mem_data_idx'), models.Index(fields=['action', '-created_at'], name='memo_hist_acao_data_idx')],
            },
        ),
    ]
