# Generated by Django 6.0.6 on 2026-07-17 02:03

import django.db.models.deletion
import memorando_remessas.models.arquivo
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorando_remessas', '0005_shipmentmemohistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMemoFile',
            fields=[
                ('id', models.BigAutoField(db_column='id_memorando_arquivo', primary_key=True, serialize=False)),
                ('file', models.FileField(db_column='arquivo', max_length=500, upload_to=memorando_remessas.models.arquivo.shipment_memo_file_upload_to, verbose_name='Arquivo')),
                ('original_name', models.CharField(db_column='nome_original', max_length=255, verbose_name='Nome original')),
                ('content_type', models.CharField(blank=True, db_column='tipo_conteudo', default='', max_length=150, verbose_name='Tipo de conteúdo')),
                ('size', models.PositiveBigIntegerField(db_column='tamanho', default=0, verbose_name='Tamanho em bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Enviado em')),
                ('shipment_memo', models.ForeignKey(db_column='id_memorando', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='memorando_remessas.shipmentmemo', verbose_name='Memorando')),
                ('uploaded_by', models.ForeignKey(db_column='enviado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_shipment_memo_files', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Arquivo do memorando',
                'verbose_name_plural': 'Arquivos dos memorandos',
                'db_table': 'memorando_remessa_arquivos',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['shipment_memo', '-created_at'], name='memo_arq_mem_data_idx')],
            },
        ),
    ]
