# Generated by Django 6.0.6 on 2026-07-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorando_remessas', '0006_shipmentmemofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmemo',
            name='cc_emails',
            field=models.JSONField(blank=True, db_column='emails_copia', default=list, help_text='Lista dos endereços que receberão uma cópia do memorando.', verbose_name='E-mails em cópia'),
        ),
        migrations.AddField(
            model_name='shipmentmemo',
            name='last_send_error',
            field=models.TextField(blank=True, db_column='ultimo_erro_envio', default='', verbose_name='Último erro de envio'),
        ),
        migrations.AddField(
            model_name='shipmentmemo',
            name='recipient_emails',
            field=models.JSONField(blank=True, db_column='emails_destinatarios', default=list, help_text='Lista dos endereços que receberão diretamente o memorando.', verbose_name='E-mails dos destinatários'),
        ),
        migrations.AlterField(
            model_name='shipmentmemo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROCESSANDO_ENVIO', 'Processando envio'), ('ENVIADO', 'Enviado'), ('FALHA_ENVIO', 'Falha no envio'), ('CANCELADO', 'Cancelado')], db_column='status', db_index=True, default='RASCUNHO', max_length=30, verbose_name='Status'),
        ),
    ]
