# Generated by Django 6.0.6 on 2026-07-17 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorando_remessas', '0007_shipmentmemo_cc_emails_shipmentmemo_last_send_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shipmentmemo',
            name='uq_memo_sequencia_revisao',
        ),
        migrations.AlterField(
            model_name='shipmentmemo',
            name='code',
            field=models.CharField(blank=True, db_column='codigo', editable=False, help_text='Código gerado pelo sistema. Exemplo: MRO21065-001.', max_length=30, null=True, verbose_name='Código'),
        ),
        migrations.AddIndex(
            model_name='shipmentmemo',
            index=models.Index(fields=['code'], name='memo_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentmemo',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('code', 'revision'), name='uq_memo_codigo_revisao'),
        ),
    ]
