# Generated by Django 6.0.6 on 2026-07-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorando_remessas', '0008_remove_shipmentmemo_uq_memo_sequencia_revisao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmemo',
            name='code',
            field=models.CharField(blank=True, db_column='codigo', editable=False, help_text='Código gerado pelo sistema. Exemplo: MR21065-001.', max_length=30, null=True, verbose_name='Código'),
        ),
    ]
