# Generated by Django 6.0.6 on 2026-07-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorando_remessas', '0009_alter_shipmentmemo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmemooption',
            name='option_type',
            field=models.CharField(choices=[('FINALIDADE', 'Finalidade')], db_column='tipo_opcao', max_length=20, verbose_name='Tipo'),
        ),
    ]
