# Generated by Django 6.0.6 on 2026-06-23 18:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(db_column='id_permissao', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='codigo', help_text='Example: proposal.view, proposal.create, purchase_order.approve', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, db_column='descricao', max_length=255, null=True)),
                ('module', models.CharField(db_column='modulo', help_text='Example: proposal, purchase_order, shipment_memo, rental', max_length=50)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissoes',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('CLIENTE', 'Cliente'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor')], db_column='tipo_usuario', max_length=20)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em')),
                ('user_origin', models.CharField(choices=[('legacy', 'Imported from Access'), ('django', 'Created in Django')], default='django', max_length=20)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('legacy_username', models.CharField(blank=True, max_length=50)),
                ('legacy_group_name', models.CharField(blank=True, max_length=100)),
                ('is_migrated_from_access', models.BooleanField(default=False)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('last_legacy_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_legacy_sync_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_sync_enabled', models.BooleanField(default=False)),
                ('approval_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('can_access_dashboard', models.BooleanField(default=False)),
                ('can_access_deductibles', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'usuarios',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(db_column='id_cliente', primary_key=True, serialize=False)),
                ('client_group', models.CharField(choices=[('DIRETORIA', 'Diretoria'), ('OPERACIONAL', 'Operacional')], db_column='grupo_cliente', max_length=20)),
                ('trade_name', models.CharField(blank=True, db_column='nome_fantasia', max_length=150, null=True)),
                ('legal_name', models.CharField(blank=True, db_column='razao_social', max_length=180, null=True)),
                ('document', models.CharField(blank=True, db_column='cnpj_cpf', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('parent_client', models.ForeignKey(blank=True, db_column='cliente_origem_id', help_text='Board/origin client related to this operational client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_clients', to='accounts.client')),
                ('user', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clientes',
                'ordering': ['trade_name', 'legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(db_column='id_colaborador', primary_key=True, serialize=False)),
                ('employee_subgroup', models.CharField(choices=[('DIRETORIA', 'Diretoria'), ('ADMINISTRATIVO', 'Administrativo'), ('ENGENHARIA', 'Engenharia'), ('OBRAS', 'Obras'), ('FINANCEIRO', 'Financeiro'), ('COMPRAS', 'Compras')], db_column='subgrupo_colaborador', max_length=30)),
                ('department', models.CharField(blank=True, db_column='departamento', max_length=100, null=True)),
                ('position', models.CharField(blank=True, db_column='cargo', max_length=100, null=True)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('user', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'colaboradores',
                'ordering': ['user__name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(db_column='id_fornecedor', primary_key=True, serialize=False)),
                ('legacy_supplier_id', models.IntegerField(blank=True, db_column='fornecedor_origem_id', null=True)),
                ('trade_name', models.CharField(blank=True, db_column='nome_fantasia', max_length=150, null=True)),
                ('legal_name', models.CharField(blank=True, db_column='razao_social', max_length=180, null=True)),
                ('document', models.CharField(blank=True, db_column='cnpj', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('user', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'fornecedores',
                'ordering': ['trade_name', 'legal_name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(db_column='id_grupo', primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('CLIENTE', 'Cliente'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor')], db_column='tipo_usuario', max_length=20)),
                ('name', models.CharField(db_column='nome_grupo', max_length=50)),
                ('description', models.TextField(blank=True, db_column='descricao', null=True)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em')),
            ],
            options={
                'verbose_name': 'User group',
                'verbose_name_plural': 'User groups',
                'db_table': 'grupos_usuario',
                'ordering': ['user_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('user_type', 'name'), name='uq_user_group_type_name')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.usergroup'),
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(db_column='id_grupo_permissao', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('permission', models.ForeignKey(db_column='id_permissao', on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='accounts.permission')),
                ('group', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='accounts.usergroup')),
            ],
            options={
                'verbose_name': 'Group permission',
                'verbose_name_plural': 'Group permissions',
                'db_table': 'grupo_permissoes',
                'ordering': ['group', 'permission'],
                'constraints': [models.UniqueConstraint(fields=('group', 'permission'), name='uq_group_permission')],
            },
        ),
    ]
