# Generated by Django 6.0.6 on 2026-06-23 18:57

import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.user.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor')], db_column='tipo_usuario', default='COLABORADOR', max_length=20),
        ),
    ]
