# Generated by Django 6.0.6 on 2026-06-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('route', models.CharField(help_text='Rota usada pelo Hub Shell. Exemplo: /financeiro', max_length=150, verbose_name='Rota')),
                ('icon', models.CharField(blank=True, default='', help_text='Nome do ícone usado no front. Exemplo: dashboard, payments, engineering.', max_length=80, verbose_name='Ícone')),
                ('desktop_enabled', models.BooleanField(default=True, verbose_name='Disponível no desktop')),
                ('mobile_enabled', models.BooleanField(default=True, verbose_name='Disponível no mobile')),
                ('mfe_enabled', models.BooleanField(default=False, verbose_name='É MFE')),
                ('legacy_enabled', models.BooleanField(default=False, verbose_name='É legado')),
                ('remote_name', models.CharField(blank=True, default='', help_text='Nome do remote no Module Federation. Exemplo: financeiro', max_length=120, verbose_name='Remote name')),
                ('remote_entry', models.CharField(blank=True, default='', help_text='URL do remoteEntry.js. Exemplo: http://localhost:4304/remoteEntry.js', max_length=255, verbose_name='Remote entry')),
                ('exposed_module', models.CharField(blank=True, default='./Routes', max_length=120, verbose_name='Exposed module')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hub_modules', to='accounts.permission', verbose_name='Permissão mínima de acesso')),
            ],
            options={
                'verbose_name': 'Módulo do Hub',
                'verbose_name_plural': 'Módulos do Hub',
                'db_table': 'hub_modulos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
