# Generated by Django 6.0.6 on 2026-07-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hubmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubmodule',
            name='favourite_mfe',
            field=models.BooleanField(default=False, verbose_name='É um MFE Favorito'),
        ),
    ]
