# Generated by Django 6.0.6 on 2026-07-03 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hubmodule_favourite_mfe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubmodule',
            name='favourite_mfe',
        ),
        migrations.CreateModel(
            name='UserHubModuleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='accounts.hubmodule', verbose_name='Módulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_module_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Favorito de módulo do usuário',
                'verbose_name_plural': 'Favoritos de módulos dos usuários',
                'db_table': 'hub_usuario_modulo_favoritos',
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='unique_user_hub_module_favorite')],
            },
        ),
    ]
