# Generated by Django 6.0.6 on 2026-07-20 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('route', models.CharField(blank=True, default='', help_text='Rota usada pelo Hub Shell. Pode ficar vazia em itens usados apenas como agrupadores.', max_length=255, verbose_name='Rota')),
                ('icon', models.CharField(blank=True, default='', max_length=80, verbose_name='Ícone')),
                ('favoritable', models.BooleanField(default=True, verbose_name='Pode ser favoritado')),
                ('desktop_enabled', models.BooleanField(default=True, verbose_name='Disponível no desktop')),
                ('mobile_enabled', models.BooleanField(default=True, verbose_name='Disponível no mobile')),
                ('legacy_enabled', models.BooleanField(default=False, verbose_name='É legado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Funcionalidade do Hub',
                'verbose_name_plural': 'Funcionalidades do Hub',
                'db_table': 'hub_itens_menu',
                'ordering': ['module__order', 'module__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserHubMenuItemFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Funcionalidade favorita do usuário',
                'verbose_name_plural': 'Funcionalidades favoritas dos usuários',
                'db_table': 'hub_usuario_item_menu_favoritos',
                'ordering': ['order', 'menu_item__order', 'menu_item__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userhubmodulefavorite',
            name='unique_user_hub_module_favorite',
        ),
        migrations.AddField(
            model_name='hubmenuitem',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='accounts.hubmodule', verbose_name='Módulo'),
        ),
        migrations.AddField(
            model_name='hubmenuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Use para agrupar funcionalidades dentro do mesmo módulo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.hubmenuitem', verbose_name='Item pai'),
        ),
        migrations.AddField(
            model_name='hubmenuitem',
            name='permission',
            field=models.ForeignKey(blank=True, help_text='Quando não informada, o item herda o acesso concedido ao módulo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hub_menu_items', to='accounts.permission', verbose_name='Permissão de acesso'),
        ),
        migrations.AddField(
            model_name='userhubmenuitemfavorite',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='accounts.hubmenuitem', verbose_name='Funcionalidade'),
        ),
        migrations.AddField(
            model_name='userhubmenuitemfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_menu_item_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.RemoveField(
            model_name='userhubmodulefavorite',
            name='module',
        ),
        migrations.RemoveField(
            model_name='userhubmodulefavorite',
            name='user',
        ),
        migrations.AddIndex(
            model_name='hubmenuitem',
            index=models.Index(fields=['module', 'parent', 'is_active', 'order'], name='hub_item_menu_tree_idx'),
        ),
        migrations.AddConstraint(
            model_name='userhubmenuitemfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'menu_item'), name='unique_user_hub_menu_item_favorite'),
        ),
        migrations.DeleteModel(
            name='UserHubModuleFavorite',
        ),
    ]
