# Generated by Django 6.0.6 on 2026-07-21 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hubmenuitem_userhubmenuitemfavorite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubmenuitem',
            name='permission',
        ),
        migrations.AddField(
            model_name='hubmenuitem',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='A funcionalidade fica visível quando o usuário possui pelo menos uma das permissões selecionadas. Sem permissões, herda o acesso do módulo.', related_name='hub_menu_items', to='accounts.permission', verbose_name='Permissões de acesso'),
        ),
        migrations.AddField(
            model_name='hubmodule',
            name='icon_color',
            field=models.CharField(default='#CC0D0E', help_text='Cor hexadecimal usada pelo ícone no front.', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida. Exemplo: #CC0D0E.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor do ícone'),
        ),
    ]
