# Generated by Django 6.0.6 on 2026-08-05 20:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('LEGACY_CATALOG', 'Catálogo legado')], default='LEGACY_CATALOG', max_length=30)),
                ('initial', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Executando'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falha')], db_index=True, default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('LEGACY', 'SGO legado'), ('HUB', 'Daruix Hub')], db_index=True, default='HUB', max_length=10)),
                ('legacy_table', models.CharField(blank=True, max_length=100)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('origin', 'legacy_table', 'legacy_id'), name='uq_composition_legacy_identity')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCompositionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicada'), ('HISTORICAL', 'Histórica'), ('ARCHIVED', 'Arquivada')], db_index=True, default='DRAFT', max_length=20)),
                ('origin', models.CharField(choices=[('LEGACY', 'SGO legado'), ('HUB', 'Daruix Hub')], default='HUB', max_length=10)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('material_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('labor_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('equipment_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
                ('legacy_payload_hash', models.CharField(blank=True, max_length=64)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='budgeting.servicecomposition')),
            ],
            options={
                'ordering': ('composition_id', '-number'),
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('LEGACY', 'SGO legado'), ('HUB', 'Daruix Hub')], db_index=True, default='HUB', max_length=10)),
                ('legacy_table', models.CharField(blank=True, max_length=100)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('description', models.CharField(db_index=True, max_length=500)),
                ('supply_type', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOR', 'Mão de obra'), ('EQUIPMENT', 'Equipamento'), ('OTHER', 'Outro')], default='OTHER', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('specification', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
                ('legacy_payload_hash', models.CharField(blank=True, max_length=64)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('description', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('origin', 'legacy_table', 'legacy_id'), name='uq_supply_legacy_identity')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCompositionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('SUPPLY', 'Insumo'), ('SUBCOMPOSITION', 'Subcomposição'), ('FREE_TEXT', 'Item livre')], default='SUPPLY', max_length=20)),
                ('description_snapshot', models.CharField(max_length=500)),
                ('unit_snapshot', models.CharField(blank=True, max_length=30)),
                ('coefficient', models.DecimalField(decimal_places=6, max_digits=18)),
                ('material_unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('labor_unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('equipment_unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcomposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_items', to='budgeting.servicecomposition')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgeting.servicecompositionversion')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='composition_items', to='budgeting.supply')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='servicecompositionversion',
            constraint=models.UniqueConstraint(fields=('composition', 'number'), name='uq_composition_version_number'),
        ),
    ]
